"""application_user

Revision ID: 7a287d6dd84d
Revises: ba954b722ca6
Create Date: 2018-03-21 09:22:33.535787

"""
import cuckoo
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a287d6dd84d'
down_revision = 'ba954b722ca6'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('user_id', cuckoo.db.types.guid.GUID(), nullable=False))
    op.create_unique_constraint(None, 'application', ['user_id'])
    op.create_foreign_key(None, 'application', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_column('application', 'user_id')
    # ### end Alembic commands ###
