"""initial

Revision ID: d55b80502a03
Revises:
Create Date: 2018-03-07 14:33:04.649503

"""
import cuckoo
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55b80502a03'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret', sa.String(length=64), nullable=False),
    sa.Column('id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('client_secret')
    )
    op.create_table('application_api_token',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('application_id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.Column('id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('job',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('params', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('schedule', cuckoo.db.types.schedule.Schedule(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.Column('application_id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_application_id'), 'job', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_application_id'), table_name='job')
    op.drop_table('job')
    op.drop_table('application_api_token')
    op.drop_table('application')
    # ### end Alembic commands ###
