"""identity

Revision ID: d63fbcaf9e5b
Revises: d55b80502a03
Create Date: 2018-03-12 11:02:36.171862

"""
import cuckoo
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd63fbcaf9e5b'
down_revision = 'd55b80502a03'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.Column('option_id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'name', name='unq_option_name')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('identity',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('id', cuckoo.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('user_id', 'provider', name='unq_identity_user')
    )
    op.create_index(op.f('ix_identity_user_id'), 'identity', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_user_id'), table_name='identity')
    op.drop_table('identity')
    op.drop_table('user')
    op.drop_table('option')
    # ### end Alembic commands ###
