"""user_id

Revision ID: fb7a5a23c059
Revises: 346c37655759
Create Date: 2018-03-19 10:12:26.669763

"""
from alembic import op
import sqlalchemy as sa
import cuckoo
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fb7a5a23c059'
down_revision = '346c37655759'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('user_id', cuckoo.db.types.guid.GUID(), nullable=False))
    op.create_unique_constraint(None, 'application', ['user_id'])
    op.create_foreign_key(None, 'application', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_column('application', 'user_id')
    # ### end Alembic commands ###
